#!/bin/bash
# chkconfig: 2345 20 80
# description: Manages the docker containers

ROOT_DIR=/opt/com.danklco.infra
COMPOSE_FILE=$ROOT_DIR/compose/docker-compose.yaml
ENV_FILE=$ROOT_DIR/compose/.env

start() {
    docker-compose -f $COMPOSE_FILE --env-file $ENV_FILE -p danklco-com-prod up -d
}

stop() {
    docker-compose -f $COMPOSE_FILE --env-file $ENV_FILE -p danklco-com-prod stop
}

case "$1" in
   start)
      start
      ;;
   stop)
      stop
      ;;
   restart)
      stop
      start
      ;;
   status)
      docker-compose -f $COMPOSE_FILE --env-file $ENV_FILE -p danklco-com-prod  ps
      ;;
   update)
      cd $ROOT_DIR
      git pull
      docker-compose -f $COMPOSE_FILE --env-file $ENV_FILE pull
      docker-compose -f $COMPOSE_FILE --env-file $ENV_FILE -p danklco-com-prod up -d --remove-orphans
      docker image prune -f
      ;;
   *)
      echo "Usage: $0 {start|stop|status|restart|update}"
esac

exit 0