name: Verify
on:
  pull_request:
    branches: [ main ]
jobs:
  env:
    GH_OWNER: klcodanr
    GROUP_ID: com.danklco.sample
    ARTIFACT_ID: ${GROUP_ID}.infra
  feature:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: s4u/maven-settings-action@v2.3.0
      with:
        # I don't love the way this works, but this is the least worst way I know
        servers: '[{"id": "github", "username": "${GH_OWNER}", "password": "${{ secrets.GH_PAT }}"},{"id": "github-${GROUP_ID}.app", "username": "${GH_OWNER}", "password": "${{ secrets.GH_PAT }}"}]'
        apacheSnapshots: true
        sonatypeSnapshots: true
    - name: Build with Maven
      run:  mvn -B package --file feature/pom.xml
    - name: Upload Features
      uses: actions/upload-artifact@v2
      with:
        name: slingosgifeature-verify
        path: |
          feature/target/slingfeature-tmp/feature-seed.json
          feature/target/slingfeature-tmp/feature-runtime.json
          feature/target/*.far
        retention-days: 1
  docker:
    runs-on: ubuntu-latest
    needs: feature
    steps:
    - uses: actions/checkout@v2
    - name: Download Features
      uses: actions/download-artifact@v2
      with:
        name: slingosgifeature-verify
        path: images/cms
    - run: ls -R images/cms
    - name: Copy Setup
      run: |
        mkdir -p images/cms/slingcms/setup/features
        cp images/cms/*.far images/cms/slingcms/setup/features
        mv images/cms/slingfeature-tmp/feature-seed.json images/cms/slingcms/setup/features
    - name: Copy Runtime
      run: |
        mkdir -p images/cms/runtime
        mv images/cms/*.far images/cms/slingfeature-tmp/feature-runtime.json images/cms/runtime
    - name: Build CMS Image
      run: |
        docker build -t cms images/cms
    - name: Build Web Image
      run: |
        docker build -t web images/web

